### ISSUE TITLE
SVG not rendered properly in Safari

### ISSUE THREAD

**Issue by MiracleVin** [markmap/markmap-vscode#25]
Can't describe how much I love this tool. Thank you so much!
when I export to html and send it to my phone, it won't open with a browser. When I save it as html on my computer, it opens with ghosting.
![图片](https://user-images.githubusercontent.com/44134530/136684387-036398df-5207-442c-b3d3-b21fdf14a9e2.png)

**Comment by gera2ld** [comment]
Safari (including browser on iPhone) has issues with SVG rendering. If that's the case, there is nothing much we can do here.

**Comment by NanYANG2015** [comment]
Hey, the HTML file exported from .mm.md source file is blank while rendering on Safari, chrome, maybe others, is there any solutions?

**Comment by gera2ld** [comment]
@hesetone @NanYANG2015 Because jsdelivr is blocked by GFW recently. It's a network problem and has nothing to do with this issue.
