### ISSUE TITLE
[Feature] Support local images

### ISSUE THREAD

**Issue by easyatgithub** [markmap/markmap-vscode#36]
how to insert a image

**Comment by tobylai-toby** [comment]
I have the same problem
<img width="33" alt="image" src="https://user-images.githubusercontent.com/60289741/184577358-7ae8a8c5-0715-4f26-874e-aab176e3012f.png">

**Comment by tobylai-toby** [comment]
@gera2ld

**Comment by joao-aguirre** [comment]
It works if the image is on the web, but it is not shown if you do not add some text to allow it to have some space, as show in [this issue](https://github.com/markmap/markmap/issues/88). 

If the image is from a local file, than it doesn't show at all. Trying to do so and checking the VSCode Developer Tools console I have found this error message:

![image-error](https://user-images.githubusercontent.com/11059665/190717476-278756cd-c624-435b-8e0c-6908890d9f43.png)

Does it give you guys any clues?

Cheers.

**Comment by jfaleiro** [comment]
is this planned to be fixed, or is there an workaround?

**Comment by gera2ld** [comment]
Let me check this weekend.

**Comment by chienhao10** [comment]
Do we have any update? Has been using alot recently when i found this extension, now got i am heavily need to include some images!

**Comment by tobylai-toby** [comment]
any updates?

**Comment by OceanBelongsToMe** [comment]
same problem!

**Comment by krissen** [comment]
Same problem. (Remote works; local does not.)

**Comment by ChanglinWu** [comment]
Also, no image, and web image sometimes also does work.
