### ISSUE TITLE
Latex expression on a branch is not rendered properly in vscode-markmap preview window

### ISSUE THREAD

**Issue by nadith** [markmap/markmap-vscode#37]
Please refer to the screenshot below. The latex expression is not rendered properly on the vscode-markmap preview window.
Ref:
![01_bug](https://user-images.githubusercontent.com/8214008/175784674-204339eb-146e-46c1-a9d7-aaff9ce8fa08.PNG)

But if I add a '.' at the end of the expression it shows it properly
Ref:
![01_fix](https://user-images.githubusercontent.com/8214008/175784681-3eb99a24-4c07-4b15-b51b-2c380715fb08.PNG)

**Comment by GrimPixel** [comment]
Something went wrong with the LaTeX support. I have even got worse problems with line breaking involving \int and probably other syntaxes.
![LaTeX](https://user-images.githubusercontent.com/39795763/218375005-3438dff6-5e20-4875-81c5-fdec8dd31c8b.png)

**Comment by gera2ld** [comment]
Should have been fixed in the latest version.
