### ISSUE TITLE
CRLF is not supported when parsing frontmatter

### ISSUE THREAD

**Issue by kebuAAA** [markmap/markmap-vscode#41]
I have read the guide but I still don't know where I should put my frontmatter. I try to put it in my markdown files but it seems not to work, Can you tell me how to configure the settings in detail? I really need this amazing extension!

**Comment by gera2ld** [comment]
Either add this to the beginning of your Markdown file (note the `markmap:` namespace):

```md
---
markmap:
  colorFreezeLevel: 2
---
```

Or this to the **Default Options** of your extension settings:

```json
{
  "colorFreezeLevel": 2
}
```

For example this is what I got with [README.md](https://github.com/markmap/markmap-vscode/blob/master/README.md) of this repo:

![image](https://user-images.githubusercontent.com/3139113/190200624-dd23df1a-f6ce-4e0a-8a1c-65c17466f0c6.png)

Please let me know if you think [the doc](https://markmap.js.org/docs/json-options) is not clear enough.

**Comment by kebuAAA** [comment]
I have done as what you said just now. The following code is in my md file. 
```markdown
---
markmap:
    colorFreezeLevel: 3
    initialExpandLevel: 1
---

# markmap

## Links

- <https://markmap.js.org/>
- [GitHub](https://github.com/gera2ld/markmap)

## Related Projects

- [coc-markmap](https://github.com/gera2ld/coc-markmap)
- [gatsby-remark-markmap](https://github.com/gera2ld/gatsby-remark-markmap)

## Features

- links
- **strong** ~~del~~ *italic* ==highlight==
- multiline
  text
- `inline code`
-
    ```js
    console.log('code block');
    ```
- Katex
  - $x = {-b \pm \sqrt{b^2-4ac} \over 2a}$
  - [More Katex Examples](#?d=gist:af76a4c245b302206b16aec503dbe07b:katex.md)
- Now we can wrap very very very very long text based on `maxWidth` option
```
I don't think the final result is what I want (In my opinion, the frontmatter doesn't work as I expect):
![image](https://user-images.githubusercontent.com/96560962/190292375-a5d7aa40-13ba-471c-aa0d-45e50584dd4d.png)
I feel very sorry for my ignorance:cry:.

**Comment by gera2ld** [comment]
I guess your end of line sequence is CRLF? Only LF is supported at the moment, let me fix this.

**Comment by kebuAAA** [comment]
> I guess your end of line sequence is CRLF? Only LF is supported at the moment, let me fix this.

Yeah, you are right, I change the end of line sequence and now the extension works well. Thank you very much.

**Comment by fanlushuai** [comment]
It's time to release  @gera2ld
