### ISSUE TITLE
Feature request: locate markdown text from the markmap

### ISSUE THREAD

**Issue by weifengsd** [markmap/markmap-vscode#42]
This feature enables us to quickly locate and edit the markdown text, which makes the markmap much more productive. Similar to the Markdown Mindmap in Atom, we can jump to the a specific text when we click on the corresponding text in the markmap. 

Wish to hear your voice on this feature.

**Comment by gera2ld** [comment]
Closing as a duplicate of #9

**Comment by gera2ld** [comment]
Implemented in #59 .
As of v0.2.4, double-clicking a node will location the source code.

**Comment by weifengsd** [comment]
Nice work, thanks！
