### ISSUE TITLE
Three capitalized words make the last word disappear

### ISSUE THREAD

**Issue by Relex12** [markmap/markmap-vscode#45]
Hi, I am not really used to open issues in open source projects, but I am struggling with this bug.

So I wanted to write this in French:
`- Alv, Alvecroft prêtresse du Culte des Grands Anciens à Nimra`
(which means the fictionnal character Alv, short for Alvecroft, is a priestess for fictionnal some cult in some fictionnal town)

but the rendered text is `Alv, Alvecroft prêtresse du Culte des Grands Anciens à` and the last word is missing for no reason. 

After playing a lot, it seems that this happens when at least three words that begin with the same letter are capitalized, Alv Alvecroft and Anciens in the example. 

If I remove one of the capital letter, the last word appears in the rendered text.

So you can reproduce, copy paste this in a file, picture of what I have as rendered below:
```
- Alv, Alvecroft prêtresse du Culte des Grands Anciens à Nimra
- Alv, Alvecroft prêtresse du Culte des grands anciens à Nimra
- Alv Alvecroft Albedo Anciens
```
![image](https://user-images.githubusercontent.com/40178652/216731449-5597ef2d-53b1-41e9-980f-6e80d79b871e.png)

**Comment by gera2ld** [comment]
Sorry I still cannot reproduce the issue.
Can you check if it is the same in [the web version of VSCode](https://vscode.dev)?

**Comment by Relex12** [comment]
Indeed, the bux doesn't seem to exist in the web version of VSCode. 

In my laptop VSCode, I have Markmap v0.0.16 installed, and my VSCode is version 1.75.0

**Comment by gera2ld** [comment]
It's likely related to local font and style. It's hard to debug it since I cannot reproduce it. Sorry about that.

**Comment by Relex12** [comment]
So there's nothing we can do to improve this? Any recomendation for future users encounting this bug?

I'll leave the issue open as it is not solved for me, you can close it if you want to

**Comment by gera2ld** [comment]
We can keep the issue open and see if we can get more information in the future.

**Comment by xiaodong2077** [comment]
os: ubuntu 18.04
vscode version: 1.77.0
markmap version: v0.0.17 (download from vscode marketplace)

Successfully reproduced this bug.
