### ISSUE TITLE
[Suggestion] ignore the front matter

### ISSUE THREAD

**Issue by fanlushuai** [markmap/markmap-vscode#46]
![image](https://user-images.githubusercontent.com/21078607/223442961-48863e46-df9e-41db-8dec-034eb5b3059e.png)

**Comment by gera2ld** [comment]
Probably duplicate of #41

**Comment by fanlushuai** [comment]
> Probably duplicate of #41

Yes, can it be directly compatible while ignoring the original format of the text

**Comment by fanlushuai** [comment]
> Probably duplicate of #41

Right. I think the problem has been fixed. Looking forward to a quick release.

Thank you for your excellent work.

**Comment by fanlushuai** [comment]
> Probably duplicate of #41

The new version 0.1.1 does not fix this issue
