### ISSUE TITLE
Not able to change the stroke colors based on a condition

### ISSUE THREAD

**Issue by usha403016** [markmap/markmap-vscode#53]
Not able to change the stroke colors based on status condition
if status =='failed' then red stroke else green stroke.
Also need to change the text color to white if the background is black.

**Comment by gera2ld** [comment]
Where does `status` come from in a Markdown? It seems out of the scope of this project.

**Comment by usha403016** [comment]
Status comes from data/Table as Failed or completed.

**Comment by usha403016** [comment]
![image](https://github.com/user-attachments/assets/10585a37-b7d9-4fff-8216-77deb152a736)
