### ISSUE TITLE
Suggestion: Add a Feature to Adjust Spacing Between Terminal Branches (Issue with Japanese Readability)

### ISSUE THREAD

**Issue by YuseiSato0302** [markmap/markmap-vscode#54]
Hello, thank you for developing such a useful extension! I’ve been using it extensively and appreciate its functionality, especially for creating mind maps. However, I would like to suggest an improvement that could enhance the user experience, particularly for those dealing with large and complex maps.

**Suggestion**
I propose adding a feature that allows users to adjust the spacing between terminal branches (leaf nodes). Currently, when there are many terminal branches, they tend to cluster together, making it difficult to visualize and organize information clearly. By allowing manual adjustments of the branch spacing, users can achieve a more intuitive layout, especially when handling larger maps.

**Use Case**
When creating large mind maps, branches can become densely packed, making it hard to distinguish between nodes. Adjusting the space between terminal branches would make the content more readable and easier to organize.
If a specific area of the mind map needs emphasis, widening the gaps between nearby branches can help visually separate them from the surrounding content.
Reason for Suggestion
The default settings work well in many cases, but when there are too many terminal branches, they become tightly clustered, which negatively affects readability. Adding a customizable spacing option would give users more control over the visual organization of their maps.

**Example with Japanese Text**
Since I am a Japanese user, I conducted testing with Japanese text, but I anticipate that similar issues could arise with other Unicode characters as well. Rather than addressing the differences between Unicode representations, allowing users to adjust the spacing between branches seems to be a more general and flexible solution. In practice, even with complex scripts like kanji or kana, adjusting the spacing between branches would significantly improve readability.

![image](https://github.com/user-attachments/assets/e83cbb35-db86-4955-a208-02e1e6d20a31)

As you can see, when the branches are too close, the Japanese characters become densely packed, making it difficult to distinguish between nodes and their content. This issue is particularly prominent in workflows where visual organization is crucial.

By considering this suggestion, I believe it could greatly enhance the accessibility and usability of your extension for a broader range of languages and users, particularly those working with complex scripts like Japanese.

**Comment by gera2ld** [comment]
In v0.1.5, you can set [`spacingVertical`](https://markmap.js.org/docs/json-options#spacingvertical) either in the *Default Options* configuration or the frontmatter of a Markdown file:

```json
{
  "spacingVertical": 10
}
```

```md
---
markmap:
  spacingVertical: 10
---
```
