### ISSUE TITLE
[Bug] Auto-Focus not working

### ISSUE THREAD

**Issue by OsicKwon** [markmap/markmap-vscode#56]
Hi,

Thank you for the great plugin for Markdown in VSCODE.
It would be really appreciated if a function that auto-focus in the preview pane works.
Just like _Markdown Preview Enhanced_
https://code.visualstudio.com/assets/docs/languages/Markdown/preview-scroll-sync.gif

![image](https://github.com/user-attachments/assets/9b264b6d-efff-41e3-999a-7bc1b382a85d)

**Comment by gera2ld** [comment]
This is actually supported but seems broken.

**Comment by OsicKwon** [comment]
That's great! However, I don't think it works perfectly with the header '---' as below

![image](https://github.com/user-attachments/assets/40419c7f-b321-4939-9b73-2539faba8793)

**Comment by gera2ld** [comment]
Fixed in 0.2.1

**Comment by OsicKwon** [comment]
> Fixed in 0.2.1

Awesome! Appreciate your super fast improvement!!!
