### ISSUE TITLE
Suggestion: Add an anchor to every branch of the markmap

### ISSUE THREAD

**Issue by sbwww** [markmap/markmap-vscode#9]
Markmap saves me a lot of time, and I think it has the potential to replace the TOC 😆 
However, we can jump to the position of the text by simply clicking on the TOC.
Adding an anchor to every branch of the markmap may be beneficial.

**Comment by gera2ld** [comment]
Implemented in #59 
As of v0.2.4, double-clicking a node will location the source code.
